##########################################
# ticker map
##########################################
ticker_map = {
    "全世界株式": ["acwi_world", "yfinance", "ACWI"],
    "米国国債長期債": ["tlt", "yfinance", "TLT"],
    "ハイイールド債スプレッド": ["hyg", "yfinance", "HYG"],
    "ドル流動性": ["uup", "yfinance", "UUP"],

    "債務サービス比率": ["dsr", "bis_quarterly", "https://stats.bis.org/api/v2/data/dataflow/BIS/WS_DSR/1.0/Q.US.P?startPeriod=2010-01-01&format=csv"],
    "企業利益": ["cp", "fred", "CP"],
    "設備投資額": ["pnfic1", "fred", "PNFIC1"],
    "商業銀行の企業向け貸出": ["busloans", "fred", "BUSLOANS"],
    "ムーディーズ社格付けBaa級社債利回り": ["baa", "fred", "BAA"],
    "ムーディーズ社格付けAaa級社債利回り": ["aaa", "fred", "AAA"],
    "実質可処分所得": ["rdpi", "fred", "DSPIC96"],
    "雇用者数": ["payems", "fred", "PAYEMS"],
    "失業率": ["unrate", "fred", "UNRATE"],
    "賃金指数": ["eciwag", "fred", "ECIWAG"],
    "労働時間（製造業）": ["awhman", "fred", "AWHMAN"],
    "住宅ローン金利（30年固定）": ["mortgage30us", "fred", "MORTGAGE30US"],
    "クレジットカード金利": ["termcbccallns", "fred", "TERMCBCCALLNS"],
    "消費者信用残高": ["totalsl", "fred", "TOTALSL"],
    "不動産向け融資残高":["realln", "fred", "REALLN"],
    "クレジットカードローンの延滞率": ["drtslcc", "fred", "DRTSCLCC"],
    "個人貯蓄率": ["PSAVERT", "fred", "PSAVERT"],
    "非農業ビジネス部門の実質時間当たり報酬": ["COMPRNFB", "fred", "COMPRNFB"],

    "グローバル流動性": ["gli", "bis_quarterly", "https://stats.bis.org/api/v2/data/dataflow/BIS/WS_GLI/1.0/Q.USD.3P.N.A.I.B.771?startPeriod=2010-01-01&format=csv"],
    "家計・非営利団体の住宅ローン残高": ["hhmsdodns", "fred", "HHMSDODNS"],
    "平均時給": ["ahe", "fred", "CES0500000003"],
    "米ドル建ての代表的代替リスクフリーレート": ["sofr", "fred", "SOFR"],
    "実効フェデラルファンド金利": ["dff", "fred", "DFF"],
    "米国3か月財務省証券利回り": ["tb3ms", "fred", "TB3MS"],
    "BBB–A 社債スプレッド": ["bbb", "fred", "BAMLC0A4CBBB"],
    "A-A 社債スプレッド": ["a", "fred", "BAMLC0A3CA"],
    "FRB総資産":["walcl", "fred", "WALCL"],
    "リバースレポ残高": ["rrpontsyd", "fred", "RRPONTSYD"],
    "準備預金残高": ["resbalns", "fred", "RESBALNS"],
    "銀行システムの総準備金": ["totresns", "fred", "TOTRESNS"],
    "TGA": ["tga", "fred", "WDTGAL"],
    "個人消費支出価格指数": ["pce", "fred", "PCE"],


    "S&P500指数": ["sp500", "yfinance", "^GSPC"],
    "NASDAQ総合指数": ["nasdaq", "yfinance", "^IXIC"],
    "Russell2000指数": ["russell2000", "yfinance", "^RUT"],
    "S&P500 セクターETF 金融": ["xlf", "yfinance", "XLF"],
    "S&P500 セクターETF テクノロジー": ["xlk", "yfinance", "XLK"],
    "S&P500 セクターETF エネルギー": ["xle", "yfinance", "XLE"],
    "S&P500 セクターETF 一般消費財": ["xly", "yfinance", "XLY"],
    "S&P500 セクターETF 生活必需品": ["xlp", "yfinance", "XLP"],
    "S&P500 セクターETF 公益事業": ["xlx", "yfinance", "XLU"],
    "S&P500構成銘柄": ["sp500_companies", "wiki", "https://en.wikipedia.org/wiki/List_of_S%26P_500_companies"],
    "VIX指数": ["vix", "fred", "VIXCLS"],
    "VIX3M指数": ["vix3m", "cboe", "https://cdn.cboe.com/api/global/us_indices/daily_prices/VIX3M_History.csv"],
    "VIX9D指数": ["vix9d", "cboe", "https://cdn.cboe.com/api/global/us_indices/daily_prices/VIX9D_History.csv"],
    "投資適格社債OAS": ["igoas", "fred", "BAMLC0A0CM"],
    "ハイイールド社債OAS": ["hyoas", "fred", "BAMLH0A0HYM2"],
    "米国10年国債利回り": ["dgs10", "fred", "DGS10"],
    "長短金利差": ["t10y2y", "fred", "T10Y2Y"],
    "金先物": ["gc=f", "yfinance", "GC=F"],
    "USD/JPY": ["usdjpy", "fred", "DEXJPUS"],
    "USD/CHF": ["usdchf", "fred", "DEXSZUS"],
    "期待インフレ率": ["t10yie", "fred", "T10YIE"],
    "ドルインデックス": ["dxy", "yfinance", "DX=F"],
    "恐怖指数": ["move", "yfinance", "^MOVE"],
    "ボラのボラ":["vvix","cboe","https://cdn.cboe.com/api/global/us_indices/daily_prices/VVIX_History.csv"],
    "ブラックスワン指数": ["skew", "yfinance", "^SKEW"],

    "日経平均": ["nikkei", "yfinance", "^N225"],
    "日本10年国債利回り": ["jp10y", "fred", "IRLTLT01JPM156N"],
    "原油": ["oil", "yfinance", "CL=F"],
    "銅": ["copper", "yfinance", "HG=F"],
    "SOX指数": ["sox", "yfinance", "^SOX"],
    "TOPIX": ["topix","stooq","https://stooq.com/q/d/l/?s=^tpx&i=d"],
    "10年物米国債インフレ連動債利回り": ["dfii10","fred","DFII10"],
    "TOPIX セクターETF 銀行": ["1615", "yfinance", "1615.T"],
    "TOPIX セクターETF 食品": ["1617", "yfinance", "1617.T"],
    "TOPIX セクターETF エネルギー": ["1618", "yfinance", "1618.T"],
    "TOPIX セクターETF 電気機器": ["1613", "yfinance", "1613.T"],
    "TOPIX セクターETF 機械": ["1621", "yfinance", "1621.T"],
    "TOPIX セクターETF 輸送用機器": ["1622", "yfinance", "1622.T"],
    "TOPIX セクターETF 鉄鋼": ["1623", "yfinance", "1623.T"],
    "TOPIX セクターETF 非鉄": ["1624", "yfinance", "1624.T"],
    "TOPIX セクターETF 化学": ["1625", "yfinance", "1625.T"],
    "TOPIX セクターETF 医薬品": ["1628", "yfinance", "1628.T"],
    "TOPIX セクターETF 小売": ["1630", "yfinance", "1630.T"],
    "TOPIX セクターETF 卸売": ["1629", "yfinance", "1629.T"],
    "TOPIX セクターETF 金融": ["1631", "yfinance", "1631.T"],
    "TOPIX セクターETF 不動産": ["1633", "yfinance", "1633.T"],
    "日経平均構成銘柄": ["nikkei_companies", "wiki", "https://ja.wikipedia.org/wiki/日経平均株価"],
    }
